### ISSUE TITLE
Fix bad coding style from NameAndTagsContainsKeywordsPredicate

### ISSUE THREAD

**Issue by chuaweiwen** [CS2103AUG2017-W14-B1/main#132]
![](https://user-images.githubusercontent.com/1023494/31875917-c3badd0a-b802-11e7-8522-c2c9a53a6a6d.png)

Bad coding style that needs to be fixed.

**Comment by chuaweiwen** [comment]
See #133 for the fix

**Comment by tshradheya** [comment]
Great.
