### ISSUE TITLE
As a user, I want to delete multiple users in one command

### ISSUE THREAD

**Issue by chuaweiwen** [CS2103AUG2017-W14-B1/main#16]
so that I can easily delete more than one person.

E.g. Delete specific persons:
delete 2, 4, 13

E.g. Delete a range of persons:
delete 5-8, 15-20

E.g. Combinations of the above examples:
delete 2, 4, 5-8, 13, 15-20

**Comment by justinpoh** [comment]
As a lazy user that looks for convenience in applications
