### ISSUE TITLE
Suggestion for improvement for nickname command

### ISSUE THREAD

**Issue by hymss** [CS2103AUG2017-W14-B1/main#185]
For the remove nickname command, according to the user guide, the command is currently 'nickname 1'. Perhaps the command name could be changed to make it more intuitive for the users, such as 'delete nickname 1'.

**Comment by tshradheya** [comment]
Can you please place the jar in a new folder and try running it

**Comment by hymss** [comment]
Hi, I tried placing the jar in a new folder and the results are still the same. Some commands work whereas others don't. Perhaps the link to your jar file (in the user guide) isn't updated.

**Comment by tshradheya** [comment]
You should download jar from releases. The jar file in UG is the AB4 given initially

**Comment by hymss** [comment]
Hi! Sorry for the late reply. Yup I downloaded the jar from the latest release when I realised your user guide link wasn't the updated one. Some of the commands still don't work as intended though!
