### ISSUE TITLE
As a user, I want to be able to auto sort whenever I add a contact

### ISSUE THREAD

**Issue by chuaweiwen** [CS2103AUG2017-W14-B1/main#19]
so that I don't have to use the sort command every single time

Toggle autosort on/off:
autosort on

If the user previously used the sort command to sort in a certain order, autosort will sort in that order.
E.g. if user sort the list in descending order, autosort will continue to sort in descending order. The order will be overwritten after the user used the sort command to sort in ascending order.

**Comment by justinpoh** [comment]
As a user who prefers my contacts to be arranged alphabetically instead of chronologically
