### ISSUE TITLE
AddReminderCommand not sure what is wrong

### ISSUE THREAD

**Issue by tanchc** [CS2103AUG2017-W14-B1/main#191]
![image](https://user-images.githubusercontent.com/31110360/32363636-4463a8be-c0ab-11e7-82cd-4a53e9f51a4d.png)
Cannot tell what is wrong with the command, the result displays unknown command but the first time "addReminder rd/Dinner with family d/25/12/2017 ti/18:00" was keyed in it passed, then the second time it had this problem so could be possible that a duplicate error has occurred. Moreover I am unable to see the reminders list so I am unable to know the status of the reminders

**Comment by tshradheya** [comment]
@justinpoh Review
