### ISSUE TITLE
Everything on track to submit?

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W14-B1/main#256]
Everything on track to submit? Remember to read submission instructions carefully and plan to finish submissions at least few hours before the deadline. All the best :+1:

**Comment by tshradheya** [comment]
Everything going fine.  @okkhoy 

We have kept `Buffer` time just in case :P 

Need to do final checking and clean up before we can submit everything
Thanks a lot

**Comment by tshradheya** [comment]
Aaaaand it done.

Closing last issue. 😄
