### ISSUE TITLE
Conventions in Naming and Terms

### ISSUE THREAD

**Issue by justinpoh** [CS2103AUG2017-W14-B1/main#58]

**Comment by justinpoh** [comment]
**iContacts** will be the name of our application. For future references to the application, either use "iContacts" (name) or "address book" (object).
**Attributes** instead of filters, to follow what is written within the Glossary and Use Case.
**Persons** when referring to multiple entries within the AddressBook.
**Data File** when referring to the XML file used to store the information of the AddressBook
**Frequently Used Contacts** to refer to the contact that we frequently Select or View

**Comment by chuaweiwen** [comment]
I think we should use "Persons" instead of "Contacts", since many class names in the program uses "Persons". But if we are referring to the list of persons, we call it "Address Book"

**Comment by tshradheya** [comment]
Using "Persons" makes sense.

As @justinpoh mentioned that Use Case 1 has `AddressBook` so let's stick to that now.
We anyways have to change the name of Software so we can easily change if same convention is followed.
