### ISSUE TITLE
Conventions for UG

### ISSUE THREAD

**Issue by edwinghy** [CS2103AUG2017-W14-B1/main#69]

**Comment by edwinghy** [comment]
**About** 
include description for both product and guide

**Getting Started** 
what users needs to know/do before they start using the product

**Feature** 
- What is the task/feature
- Include visuals
- Basic features to complicated features
- 1 Task per section
- 1 step per bullet point
- Organize information in order
- Avoid cross referencing especially forward referencing

**Instructions**
in point form to reduce errors made by user

**Shortcuts**
table form

**Comment by edwinghy** [comment]
Use San Sarif Fonts - Fonts with no flourishes in design

**Comment by edwinghy** [comment]
Command Format - Blue?
Mark up - Green?
Call out - Orange?

**Comment by edwinghy** [comment]
command format first before the example

**Comment by edwinghy** [comment]
main heading - title case eg. Getting Started
sub heading - sentence case Visual walkthrough
names to start with captical letters

**Comment by chuaweiwen** [comment]
San Serif fonts examples: Arial, Helvetica, Tahoma, Verdana
For code: Courier, Consolas
Don't use Serif fonts: e.g. Time News Roman
